### ISSUE TITLE
As a data scientist, I want to be able to generate automated test results for Nachet Interactive's Models

### ISSUE THREAD

**Issue by MaxenceGui** [ai-cfia/api-test#17]
### Description :rocket:

As Nachet Interactive progresses, a standard way to test and compare the performance of the various models used becomes necessary to provide good data and value to the data scientist. These automated tests will help them in their decision making developing new models for the application. The accuracy objective of the models described in our milestones is 90%, having these tests will help provide a good overview of the models and find the most performant one.

### Steps by Steps :clipboard:

- Defined the objectives of the test
- Define relevant metrics
- Prepare test data from the blob storage
- Implement the automated tests
- Execute tests
- Documents and communicate
- Produce test reports

### Acceptance Criteria :white_check_mark:

- All test data, including models' results, are recorded
- The implemented data visualizer effectively presents the results of the tests, enhancing data analysis capabilities.

### Tasks 🛠️

- [ ] Gather and prepare the test data
- [ ] Start the command line testing application for Nachet
- [ ] Refactor Finesse functions into more general ones that can do work for Finesse and Nachets
- [ ] Record all tests run
- [ ] Builds tools to create report tests
- [ ] Build and maintain testing documentation (Wiki, GitHub, etc.)
