### ISSUE TITLE
Add URL Download Option for Query Files for `finesse_test` in `api-test`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/api-test#21]
## Description
Currently, `finesse_test.py` in `api-test` supports using a local path for query files with `--path`. This change would enable specifying a URL to download query files directly but only when using `finesse_test.py`.

## Tasks
- [ ] Add a `--url` command line option to `finesse_test.py` for specifying a remote URL.
- [ ] Implement functionality to download files from this URL to a temporary directory.
- [ ] Ensure these downloaded files are used for query execution in `finesse_test.py`.
- [ ] Update tests
- [ ] Update docs

## Acceptance Criteria
- `finesse_test.py` accepts a remote URL with `--url`.
- Files are successfully downloaded from the URL.
