### ISSUE TITLE
Compare Finesse's Score Against a Public Search Engine for Accuracy Comparison

### ISSUE THREAD

**Issue by ibrahim-kabir** [ai-cfia/api-test#6]
## Summary
We aim to compare Finesse's Score with what a Bing search engine could produce. Bing search engines stands as our primary competitor, and it would be highly beneficial to ascertain whether our tool competes or even outperforms them. This evaluation would significantly enhance the accuracy assessment of Finesse.

## Tasks
- [x] Research and select a public search engine to compare with
- [x] Update the script with the public search engine
- [x] Filter of user queries to test only those containing at least one inspection.canada.ca URL. 
- [x] Test of user queries. Saving these queries in the results of the Finesse accuracy test.

## Acceptance Criteria
* Finesse's accuracy can be compared with the Bing search accuracy score in API tests and functions for markdown, CSV, and logging
* The integration should not affect the performance or functionality of existing features
* The comparison mechanism should clearly display the difference in accuracy between Finesse and the Bing search

**Comment by rngadam** [comment]
@ibrahim-kabir create a draft pull request from your branch so we have early visibility into your work
